---
- hosts: junction

  tasks:
        - name: apt-get update
          apt: update_cache=yes
          sudo: yes

        - name: install dependencies
          apt: name=bluetooth,vorbis-tools,python-cwiid,wminput,libsamplerate0-dev,libasound2-dev,libspeexdsp-dev,alsa-utils,xboxdrv
          sudo: yes

        - name: fix audio driver
          lineinfile: dest=/etc/modprobe.d/alsa-base.conf regexp="snd_bcm2835" line="options snd_bcm2835 index=1" state=present
          sudo: yes

        - name: add pmc to audio and input groups
          user: name=pmc groups=audio,input append=yes
          sudo: yes

        - name: add uinput to /etc/modules
          lineinfile: dest=/etc/modules regexp="uinput" line="uinput" state=present
          sudo: yes

        - name: add joydev to /etc/modules
          lineinfile: dest=/etc/modules regexp="joydev" line="joydev" state=present
          sudo: yes

        - name: add udev rule
          shell: echo 'KERNEL=="uinput", MODE="0666"' > /etc/udev/rules.d/wiimote.rules creates=/etc/udev/rules.d/wiimote.rules
          sudo: yes

        - name: clone RetroArch
          git: repo=git://github.com/libretro/RetroArch.git dest=/home/pmc/RetroArch update=no
          sudo: yes
          sudo_user: pmc

        - name: compile RetroArch
          shell: 'CFLAGS="-O3 -mfpu=neon-vfpv4 -mfloat-abi=hard" ./configure --disable-x11 --enable-floathard --disable-ffmpeg  --enable-udev --disable-pulse --disable-oss --enable-neon --disable-netplay && make clean && make -j2 creates=/home/pmc/RetroArch/retroarch'
          sudo: yes
          sudo_user: pmc
          args:
            chdir: /home/pmc/RetroArch

        - name: clone fceumm
          git: repo=git://github.com/libretro/libretro-fceumm.git dest=/home/pmc/libretro-fceumm update=no
          sudo: yes
          sudo_user: pmc

        - name: compile fceumm
          shell: 'CFLAGS="-O3 -mfpu=neon-vfpv4 -mfloat-abi=hard" make -j2 -f Makefile.libretro creates=/home/pmc/libretro-fceumm/fceumm_libretro.so'
          sudo: yes
          sudo_user: pmc
          args:
            chdir: /home/pmc/libretro-fceumm

        - name: install fceumm
          shell: cp /home/pmc/libretro-fceumm/fceumm_libretro.so /home/pmc/RetroArch/ creates=/home/pmc/RetroArch/fceumm_libretro.so
          sudo: yes
          sudo_user: pmc

        - name: clone picodrive
          git: repo=git://github.com/libretro/picodrive.git dest=/home/pmc/picodrive update=no
          sudo: yes
          sudo_user: pmc

        - name: compile picodrive
          shell: 'CFLAGS="-O3 -mfpu=neon-vfpv4 -mfloat-abi=hard" make -j2 -f Makefile.libretro creates=/home/pmc/picodrive/picodrive_libretro.so'
          sudo: yes
          sudo_user: pmc
          args:
            chdir: /home/pmc/picodrive

        - name: install picodrive
          shell: cp /home/pmc/picodrive/picodrive_libretro.so /home/pmc/RetroArch/ creates=/home/pmc/RetroArch/picodrive_libretro.so
          sudo: yes
          sudo_user: pmc

        - name: clone snes9x repo
          git: repo=git://github.com/libretro/snes9x-next.git dest=/home/pmc/snes9x-next update=no
          sudo: yes
          sudo_user: pmc

        - name: compile snes9x
          shell: 'CFLAGS="-O3 -mfpu=neon-vfpv4 -mfloat-abi=hard" make -j2 -f Makefile.libretro platform=armvneon creates=/home/pmc/snes9x-next/snes9x_next_libretro.so'
          sudo: yes
          sudo_user: pmc
          args:
            chdir: /home/pmc/snes9x-next

        - name: install snes9x
          shell: cp /home/pmc/snes9x-next/snes9x_next_libretro.so /home/pmc/RetroArch/ creates=/home/pmc/RetroArch/snes9x_next_libretro.so
          sudo: yes
          sudo_user: pmc

        - name: clone pocketsnes repo
          git: repo=git://github.com/libretro/pocketsnes-libretro.git dest=/home/pmc/pocketsnes-libretro update=no
          sudo: yes
          sudo_user: pmc

        - name: compile pocketsnes
          shell: 'CFLAGS="-O3 -mfpu=neon-vfpv4 -mfloat-abi=hard" make -j2 creates=/home/pmc/pocketsnes-libretro/libretro.so'
          sudo: yes
          sudo_user: pmc
          args:
            chdir: /home/pmc/pocketsnes-libretro

        - name: install pocketsnes
          shell: cp /home/pmc/pocketsnes-libretro/libretro.so /home/pmc/RetroArch/pocketsnes_libretro.so creates=/home/pmc/RetroArch/pocketsnes_libretro.so
          sudo: yes
          sudo_user: pmc

        - name: clone gpsp
          git: repo=git://github.com/libretro/gpsp.git dest=/home/pmc/gpsp update=no
          sudo: yes
          sudo_user: pmc

        - name: compile gpsp
          shell: 'CFLAGS="-O3 -mfpu=neon-vfpv4 -mfloat-abi=hard" make -j2 creates=/home/pmc/gpsp/gpsp_libretro.so'
          sudo: yes
          sudo_user: pmc
          args:
            chdir: /home/pmc/gpsp

        - name: install gpsp
          shell: cp /home/pmc/gpsp/gpsp_libretro.so /home/pmc/RetroArch/ creates=/home/pmc/RetroArch/gpsp_libretro.so
          sudo: yes
          sudo_user: pmc
