---
- hosts: junction

  handlers:
        - name: Restart ssh
          action: service name=ssh state=restarted

        - name: Mount paul
          shell: mount -a
          sudo: yes

  tasks:
        - name: apt-get update
          apt: update_cache=yes
          sudo: yes

        - name: Disallow password authentication
          lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
          notify: Restart ssh
          sudo: yes

        - name: omxplayer
          apt: name=omxplayer state=present
          sudo: yes

        - name: git
          apt: name=git state=present
          sudo: yes

        - name: sqlite
          apt: name=sqlite3 state=present
          sudo: yes

        - name: create pmc user
          user: name=pmc group=video
          sudo: yes

        - name: create paul mount dir
          file: name=/media/paul state=directory
          sudo: yes

        - name: automatically mount paul
          lineinfile: dest=/etc/fstab regexp="/media/paul" line="/dev/disk/by-uuid/feb11725-a136-4b94-8ad9-079bfc2d1d3e /media/paul ext4 defaults,noatime 0 0" state=present
          sudo: yes
          notify: Mount paul

        - name: clone pi-media-controller repo
          git: repo=https://github.com/sartak/pi-media-controller.git dest=/home/pmc/pi-media-controller update=no
          sudo: yes
          sudo_user: pmc

        - name: install perl dependencies
          apt: name=twiggy,libutf8-all-perl,libjson-perl,libmouse-perl,libdbd-sqlite3-perl,libfile-next-perl,libmp4-info-perl,libimage-exiftool-perl,libfile-slurp-perl,libxml-libxml-perl,libxml-libxml-lazybuilder-perl,libpackage-new-perl,libnet-upnp-perl,libdigest-sha-perl,libanyevent-http-perl,libipc-run3-perl,libcarp-always-perl
          sudo: yes

        - name: install useful tools
          apt: name=screen,vim,lsof
          sudo: yes

        - name: install config
          file: dest=/home/pmc/pi-media-controller/config.json src=/media/paul/pmc.config state=link force=yes
          sudo: yes
          sudo_user: pmc

        - name: fix screen attaching as pmc
          lineinfile: dest=/home/pi/.bashrc regexp="sudo chown pmc `tty`" line="sudo chown pmc `tty`" state=present
          sudo: yes

        - name: PMC_DATABASE
          lineinfile: dest=/home/pmc/.bashrc regexp="PMC_DATABASE=" line="export PMC_DATABASE=/media/paul/media.sqlite" state=present
          sudo: yes
          sudo_user: pmc

        - name: disable login noise
          file: dest=/home/pi/.hushlogin state=touch

        - name: install boot cron job
          cron: special_time=reboot name="pmc boot" user=pmc job="/bin/bash --login -c 'sleep 5; cd /home/pmc/pi-media-controller; PMC_DATABASE=/media/paul/media.sqlite PMC_LOCATION=Living\ Room screen -dmUS pmc twiggy -Ilib -Iextlib'"
          sudo: yes

        - name: install backup cron job
          cron: special_time=hourly name="pmc backup" user=pmc job="/bin/bash --login -c 'cp /media/paul/media.sqlite tmp.sqlite; mv tmp.sqlite /media/paul/backup/media-$(shasum tmp.sqlite | perl -e \"<> =~ /^(\w+) /; print \$1\").sqlite'"
          sudo: yes

        - name: gpu_mem
          lineinfile: dest=/boot/config.txt regexp="^gpu_mem=" line="gpu_mem=128" state=present
          sudo: yes

