---
- hosts: tleilax

  handlers:
        - name: Restart ssh
          action: service name=ssh state=restarted

        - name: Mount leto
          shell: mount -a
          sudo: yes

  tasks:
        - name: apt-get update
          apt: update_cache=yes
          sudo: yes

        - name: Disallow password authentication
          lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
          notify: Restart ssh
          sudo: yes

        - name: nginx
          apt: name=nginx state=present
          sudo: yes

        - name: Remove default nginx page
          file: name=/etc/nginx/sites-enabled/default state=absent
          sudo: yes

        - name: sqlite
          apt: name=sqlite3 state=present
          sudo: yes

        - name: create pmc user
          user: name=pmc group=video
          sudo: yes

        - name: exfat-utils
           apt: name=exfat-utils state=present
          sudo: yes

        - name: automatically mount leto
        lineinfile: dest=/etc/fstab regexp="/media/leto" line="/dev/disk/by-uuid/542D-BC8D /media/leto exfat defaults,dmask=0000,fmask=0000,utf8,noatime,auto 0 0" state=present
          sudo: yes
          notify: Mount leto

        - name: clone pi-media-controller repo
          git: repo=https://github.com/sartak/pi-media-controller.git dest=/home/pmc/pi-media-controller
          sudo: yes
          sudo_user: pmc

        - name: install perl dependencies
          apt: name=twiggy,libutf8-all-perl,libjson-perl,libmouse-perl,libdbd-sqlite3-perl,libfile-next-perl,libmp4-info-perl,libimage-exiftool-perl,libfile-slurp-perl
          sudo: yes

        - name: install screen
          apt: name=screen
          sudo: yes

        - name: disable login noise
          file: dest=/home/pi/.hushlogin state=touch

        - name: install boot cron job
          cron: special_time=reboot name="pmc" user=pmc job="/bin/bash --login -c 'cd /home/pmc/pi-media-controller; PMC_HOST=10.0.1.13 PMC_DATABASE=/media/leto/media.sqlite screen -dmUS pmc twiggy -Ilib -Iextlib'"
          sudo: yes

        - name: install backup cron job
          cron: special_time=hourly name="pmc" user=pmc job="/bin/bash --login -c 'cp /media/leto/media.sqlite tmp.sqlite; mv tmp.sqlite /media/leto/backup/media-$(shasum tmp.sqlite | perl -e "<> =~ /^(\w+) /; print \$1").sqlite'"
          sudo: yes
